package com.fuyi.web_inter;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-10-24T15:46:51.654+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "HiServiceService", 
                  wsdlLocation = "http://localhost:8010/ws_cxf_web/services/hi?wsdl",
                  targetNamespace = "http://inter.ws_cxf_web/") 
public class HiServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://inter.ws_cxf_web/", "HiServiceService");
    public final static QName HiServicePort = new QName("http://inter.ws_cxf_web/", "HiServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8010/ws_cxf_web/services/hi?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HiServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8010/ws_cxf_web/services/hi?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HiServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HiServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HiServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HiServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HiServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HiServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HiService
     */
    @WebEndpoint(name = "HiServicePort")
    public HiService getHiServicePort() {
        return super.getPort(HiServicePort, HiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HiService
     */
    @WebEndpoint(name = "HiServicePort")
    public HiService getHiServicePort(WebServiceFeature... features) {
        return super.getPort(HiServicePort, HiService.class, features);
    }

}
