
package com.fuyi.person;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://ws.fuyi.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://ws.fuyi.com/", className = "com.fuyi.person.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://ws.fuyi.com/", className = "com.fuyi.person.AddPersonResponse")
    @Action(input = "http://ws.fuyi.com/PersonService/addPersonRequest", output = "http://ws.fuyi.com/PersonService/addPersonResponse")
    public void addPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.fuyi.person.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPerson", targetNamespace = "http://ws.fuyi.com/", className = "com.fuyi.person.GetAllPerson")
    @ResponseWrapper(localName = "getAllPersonResponse", targetNamespace = "http://ws.fuyi.com/", className = "com.fuyi.person.GetAllPersonResponse")
    @Action(input = "http://ws.fuyi.com/PersonService/getAllPersonRequest", output = "http://ws.fuyi.com/PersonService/getAllPersonResponse")
    public List<Person> getAllPerson();

}
