package com.fuyi.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-10-24T11:41:17.565+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws_cxf_server/", name = "HelloServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloServicePortType {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws_cxf_server/", className = "com.fuyi.stub.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws_cxf_server/", className = "com.fuyi.stub.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "http://ws_cxf_server/")
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "http://ws_cxf_server/")
        java.lang.String name
    );
}
