package com.fuyi.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-10-24T15:35:38.899+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws_cxf_web/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://ws_cxf_web/", className = "com.fuyi.web.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://ws_cxf_web/", className = "com.fuyi.web.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
